### ISSUE TITLE
Images?

### ISSUE THREAD

**Issue by vosmani** [WereCatf/source#2]
Hi WereCatf,

Would you consider making compiled images available for download for people like myself, not well versed in building images, but very interested in using your image?

**Comment by WereCatf** [comment]
I suppose I could, but I'd have to rent a VPS to hold all the files -- if I was doing it, I'd want to do it properly, instead of via Dropbox-links or such. There is also the fact that I cannot commit to any specific release-schedules, I do not offer support on using LEDE, due to depression and such I just do not have the capacity for such.

Mind if I ask why do you wish to use my images, tho? Is there some specific issue you're having with the Onion-ones, like e.g. some missing kernel-modules or something?

**Comment by vosmani** [comment]
Thanks WereCatf. Yes, the main issue is the availability (or rather non-availability) of kernel modules from the Onion repo, especially kmods related to iptables and support for external adapters. From what I've read, your image provides the best trade-off between WiFi performance and freedom to install kmods.

Of course, I wouldn't expect any support on the image or its use. I thought it would be the case of uploading your image here on the release section of the project? Or perhaps it is more complex than that?

**Comment by WereCatf** [comment]
It's just an ugly solution. It'd be much neater if I had an actual website for this stuff and a repo of my own, but I guess I'll make a release here on github today or tomorrow and think about the long term later.

Oh, and as for WiFi-performance: it's gotten a lot better as of late. It's not stalling anymore, at least what little I've tested, and I am getting something around ~1.6MB/s download-speeds on it -- it's still slower, but not unuseable anymore.

**Comment by WereCatf** [comment]
Well, I made a first try at a release via github. Never done it before and I may tweak things, if I do more releases in the future, but there is the first release ever, now.

**Comment by vosmani** [comment]
Thanks very much WereCatf for this meticulous release! It's an example for what @OnionIoT team should have provided, as promised.

I've also tested the WiFi and it seems it is not stalling anymore, however the disconnects are quite frequent. So, I ended up plugging an external adapter and disabled on board WiFi.

**Comment by WereCatf** [comment]
I don't understand why they refuse to just compile all the kernel-modules, it's not like it increases compilation-time by more than ~30 seconds or so. Oh well.

I'll close this issue now, then. Feel free to open a new one, if there's some improvements you can think of or you spot something I've messed up, otherwise happy to be of service.
